dist: trusty
os: linux
language: node_js
node_js:
  - '8.12'

branches:
  only:
    - development

cache:
  yarn: true
  timeout: 600
  directories:
    - $HOME/.electron
    - .eslintcache
    - $HOME/.cache/electron-builder

install:
  - yarn install --force

script:
  - ./spectral
